exclude: >
  (?x)^(
      alembic/.*|
      clients/.*|
      .*/__init__.py|
      .*_pb2.py|
      .*_pb2_grpc.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: no-commit-to-branch
    - id: requirements-txt-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies: [
            flake8-comprehensions,
            flake8-bugbear,
            flake8-print,
        ]
